[package]
name = "snark-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
ark-ff = "0.5.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"
r1cs = "0.4.7"
tempfile = "3.20.0"
tokio = { version = "1.45.1", features = ["full"] }
