[package]
name = "snark-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
byteorder = "1.5.0"
libc = "0.2.172"
num-bigint = "0.4.6"
tokio = { version = "1.45.1", features = ["full"] }
